# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlackCow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#pod 'Google-Mobile-Ads-SDK'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'


  # Pods for BlackCow

end
